import { registerCategory } from '../registry';
import type { ShaderCategory } from '../types';

const basics: ShaderCategory = {
  id: 'basics',
  title: 'Shader Basics',
  titleZh: 'Shader 基础',
  description:
    'From noise and fractals to lighting and shapes — the essential building blocks of fragment shaders.',
  descriptionZh: '从噪声、分形到光照与形状——片元着色器的核心构建基石。',
  cardType: 'shader',
  series: [
    {
      id: 'colors',
      title: 'Colors & Gradients',
      titleZh: '色彩与渐变',
      description: 'Dynamic gradients and smooth color transitions with real-time control.',
      descriptionZh: '动态渐变与平滑色彩过渡，实时参数控制。',
      demos: [
        {
          id: 'gradient-ring',
          title: 'Gradient Ring',
          titleZh: '渐变光环',
          description: 'Dynamic circular gradient with palette rotation and hue shifting.',
          descriptionZh: '动态环形渐变，可调色盘旋转变换。',
          source: 'basics/colors/02-gradient-ring.glsl',
          params: [
            {
              name: 'u_speed',
              label: 'Speed',
              labelZh: '速度',
              min: 0,
              max: 5,
              step: 0.1,
              default: 1.0,
            },
            {
              name: 'u_hue_shift',
              label: 'Hue Shift',
              labelZh: '色相偏移',
              min: 0,
              max: 1,
              step: 0.01,
              default: 0.0,
            },
          ],
          presets: [
            { name: 'slow', nameZh: '慢速', values: { u_speed: 0.3, u_hue_shift: 0.0 } },
            { name: 'normal', nameZh: '正常', values: { u_speed: 1.0, u_hue_shift: 0.25 } },
            { name: 'fast', nameZh: '快速', values: { u_speed: 3.0, u_hue_shift: 0.5 } },
          ],
        },
        {
          id: 'mix-smoothstep',
          title: 'mix() vs smoothstep()',
          titleZh: 'mix 与 smoothstep 对比',
          description:
            'Side-by-side comparison of linear mix and smooth Hermite interpolation with edge coloring.',
          descriptionZh: '线性 mix 与 smoothstep 的直观对比，可调边缘着色。',
          source: 'basics/colors/03-mix-smoothstep.glsl',
          params: [
            {
              name: 'u_transition',
              label: 'Transition',
              labelZh: '过渡位置',
              min: 0,
              max: 1,
              step: 0.01,
              default: 0.5,
            },
            {
              name: 'u_color_a',
              label: 'Color A',
              labelZh: '颜色A',
              type: 'color',
              defaultColor: [0.05, 0.08, 0.25],
            },
            {
              name: 'u_color_b',
              label: 'Color B',
              labelZh: '颜色B',
              type: 'color',
              defaultColor: [0.9, 0.5, 0.3],
            },
          ],
          presets: [
            {
              name: 'default',
              nameZh: '默认',
              values: {
                u_transition: 0.5,
                u_color_a: [0.05, 0.08, 0.25],
                u_color_b: [0.9, 0.5, 0.3],
              },
            },
            {
              name: 'sunset',
              nameZh: '日落',
              values: { u_transition: 0.6, u_color_a: [0.1, 0.0, 0.2], u_color_b: [1.0, 0.4, 0.0] },
            },
            {
              name: 'ocean',
              nameZh: '海洋',
              values: { u_transition: 0.4, u_color_a: [0.0, 0.2, 0.3], u_color_b: [0.2, 0.7, 0.8] },
            },
          ],
        },
      ],
    },
    {
      id: 'coordinates',
      title: 'Coordinate Systems',
      titleZh: '坐标系变换',
      description: 'Polar coordinates and geometric transformations.',
      descriptionZh: '极坐标与几何变换的视觉呈现。',
      demos: [
        {
          id: 'polar-flower',
          title: 'Polar Flower',
          titleZh: '极坐标之花',
          description:
            'Beautiful polar-coordinate patterns with adjustable petal count and radius.',
          descriptionZh: '极坐标生成的美丽花纹图案，可调花瓣数和半径。',
          source: 'basics/coordinates/01-polar-flower.glsl',
          params: [
            {
              name: 'u_petals',
              label: 'Petals',
              labelZh: '花瓣数',
              min: 2,
              max: 16,
              step: 1,
              default: 6,
            },
            {
              name: 'u_radius',
              label: 'Radius',
              labelZh: '半径',
              min: 0.3,
              max: 1.5,
              step: 0.05,
              default: 1.0,
            },
          ],
          presets: [
            { name: 'rose', nameZh: '玫瑰', values: { u_petals: 5, u_radius: 1.0 } },
            { name: 'daisy', nameZh: '雏菊', values: { u_petals: 8, u_radius: 0.8 } },
            { name: 'sunflower', nameZh: '向日葵', values: { u_petals: 12, u_radius: 1.2 } },
          ],
        },
      ],
    },
    {
      id: 'fractals',
      title: 'Fractals',
      titleZh: '分形',
      description: 'Classic Mandelbrot and Julia sets with interactive zoom.',
      descriptionZh: '经典 Mandelbrot 和 Julia 集合，交互式缩放探索。',
      demos: [
        {
          id: 'mandelbrot',
          title: 'Mandelbrot Set',
          titleZh: 'Mandelbrot 集合',
          description: 'The iconic fractal with smooth coloring and real-time zoom.',
          descriptionZh: '标志性分形，平滑着色与实时缩放。',
          source: 'basics/fractals/01-mandelbrot.glsl',
          params: [
            {
              name: 'u_zoom',
              label: 'Zoom',
              labelZh: '缩放',
              min: 0.3,
              max: 4,
              step: 0.05,
              default: 1.2,
            },
            {
              name: 'u_iterations',
              label: 'Iterations',
              labelZh: '迭代次数',
              min: 20,
              max: 150,
              step: 1,
              default: 60,
            },
            {
              name: 'u_color_theme',
              label: 'Theme',
              labelZh: '配色主题',
              min: 0,
              max: 3,
              step: 1,
              default: 0,
            },
          ],
          presets: [
            {
              name: 'classic',
              nameZh: '经典',
              values: { u_zoom: 1.2, u_iterations: 60, u_color_theme: 0 },
            },
            {
              name: 'deep',
              nameZh: '深探',
              values: { u_zoom: 3.2, u_iterations: 120, u_color_theme: 1 },
            },
            {
              name: 'neon',
              nameZh: '霓虹',
              values: { u_zoom: 2.0, u_iterations: 80, u_color_theme: 2 },
            },
          ],
        },
        {
          id: 'julia',
          title: 'Julia Set',
          titleZh: 'Julia 集合',
          description: 'Animated Julia set with real-time constant C control via parameters.',
          descriptionZh: '动画 Julia 集合，参数控制实常数 C。',
          source: 'basics/fractals/02-julia.glsl',
          params: [
            {
              name: 'u_c_real',
              label: 'C Real',
              labelZh: 'C 实部',
              min: -1,
              max: 1,
              step: 0.01,
              default: -0.7,
            },
            {
              name: 'u_c_imag',
              label: 'C Imag',
              labelZh: 'C 虚部',
              min: -1,
              max: 1,
              step: 0.01,
              default: 0.27,
            },
            {
              name: 'u_zoom',
              label: 'Zoom',
              labelZh: '缩放',
              min: 0.5,
              max: 3,
              step: 0.05,
              default: 1.5,
            },
          ],
          presets: [
            {
              name: 'seahorse',
              nameZh: '海马',
              values: { u_c_real: -0.75, u_c_imag: 0.11, u_zoom: 1.8 },
            },
            {
              name: 'spiral',
              nameZh: '螺旋',
              values: { u_c_real: -0.7, u_c_imag: 0.27, u_zoom: 1.5 },
            },
            {
              name: 'dendrite',
              nameZh: '树突',
              values: { u_c_real: 0.28, u_c_imag: 0.008, u_zoom: 2.0 },
            },
          ],
        },
      ],
    },
    {
      id: 'lighting',
      title: 'Lighting & Materials',
      titleZh: '光照与材质',
      description: 'Physically-inspired light scattering and refraction effects.',
      descriptionZh: '物理启发的光散射与折射效果。',
      demos: [
        {
          id: 'water-droplet',
          title: 'Water Droplet',
          titleZh: '水滴折射',
          description:
            'Realistic water droplet with refraction, caustics, and adjustable drop size.',
          descriptionZh: '逼真水滴折射与焦散效果，可调水滴大小。',
          source: 'basics/lighting/03-water-droplet.glsl',
          params: [
            {
              name: 'u_refraction',
              label: 'Refraction',
              labelZh: '折射率',
              min: 0.5,
              max: 2.0,
              step: 0.05,
              default: 1.33,
            },
            {
              name: 'u_drop_size',
              label: 'Drop Size',
              labelZh: '水滴大小',
              min: 0.1,
              max: 0.6,
              step: 0.02,
              default: 0.25,
            },
          ],
          presets: [
            { name: 'water', nameZh: '水', values: { u_refraction: 1.33, u_drop_size: 0.25 } },
            { name: 'glass', nameZh: '玻璃', values: { u_refraction: 1.5, u_drop_size: 0.35 } },
            { name: 'diamond', nameZh: '钻石', values: { u_refraction: 2.0, u_drop_size: 0.18 } },
          ],
        },
      ],
    },
    {
      id: 'noise',
      title: 'Noise & Texture',
      titleZh: '噪声与纹理',
      description: 'Procedural noise techniques with domain warping for organic textures.',
      descriptionZh: '程序化噪声技法，域扭曲生成有机纹理。',
      demos: [
        {
          id: 'domain-warp',
          title: 'Domain Warp',
          titleZh: '域扭曲',
          description:
            'Fractal Brownian motion with multi-layer domain warping producing organic, marble-like textures.',
          descriptionZh: '多层域扭曲的分形布朗运动，产生有机大理石的纹理效果。',
          source: 'basics/noise/03-domain-warp.glsl',
          params: [
            {
              name: 'u_warp',
              label: 'Warp',
              labelZh: '扭曲强度',
              min: 0.2,
              max: 5,
              step: 0.1,
              default: 2.0,
            },
            {
              name: 'u_color1',
              label: 'Color 1',
              labelZh: '颜色1',
              type: 'color',
              defaultColor: [0.05, 0.08, 0.25],
            },
            {
              name: 'u_color2',
              label: 'Color 2',
              labelZh: '颜色2',
              type: 'color',
              defaultColor: [0.1, 0.4, 0.7],
            },
          ],
          presets: [
            {
              name: 'nebula',
              nameZh: '星云',
              values: { u_warp: 2.0, u_color1: [0.05, 0.08, 0.25], u_color2: [0.1, 0.4, 0.7] },
            },
            {
              name: 'marble',
              nameZh: '大理石',
              values: { u_warp: 1.5, u_color1: [0.9, 0.85, 0.8], u_color2: [0.4, 0.35, 0.3] },
            },
            {
              name: 'lava',
              nameZh: '熔岩',
              values: { u_warp: 3.0, u_color1: [0.8, 0.2, 0.0], u_color2: [1.0, 0.7, 0.0] },
            },
          ],
        },
      ],
    },
    {
      id: 'shapes',
      title: 'Signed Distance Functions',
      titleZh: '距离场形状',
      description: 'Geometric SDF compositions with soft shadows and edge effects.',
      descriptionZh: '几何距离场组合，软阴影与边缘效果。',
      demos: [
        {
          id: 'hexagon-ring',
          title: 'Hexagon Ring',
          titleZh: '六边形环',
          description: 'A rotating ring of hexagons with smooth blending and color cycling.',
          descriptionZh: '旋转的六边形环，平滑混合与颜色循环。',
          source: 'basics/shapes/03-hexagon-ring.glsl',
          params: [
            {
              name: 'u_ring_count',
              label: 'Ring Count',
              labelZh: '环数',
              min: 3,
              max: 12,
              step: 1,
              default: 6,
            },
            {
              name: 'u_rotation_speed',
              label: 'Rotation',
              labelZh: '旋转速度',
              min: 0,
              max: 3,
              step: 0.1,
              default: 0.5,
            },
            {
              name: 'u_accent_color',
              label: 'Accent',
              labelZh: '强调色',
              type: 'color',
              defaultColor: [0.8, 0.5, 0.9],
            },
          ],
          presets: [
            {
              name: 'honeycomb',
              nameZh: '蜂巢',
              values: { u_ring_count: 6, u_rotation_speed: 0.5, u_accent_color: [0.8, 0.5, 0.9] },
            },
            {
              name: 'wheel',
              nameZh: '轮盘',
              values: { u_ring_count: 8, u_rotation_speed: 1.2, u_accent_color: [0.2, 0.7, 0.9] },
            },
            {
              name: 'minimal',
              nameZh: '极简',
              values: { u_ring_count: 4, u_rotation_speed: 0.3, u_accent_color: [0.9, 0.6, 0.3] },
            },
          ],
        },
      ],
    },
  ],
};

registerCategory(basics);
