import { registerCategory } from '../registry';
import type { ShaderCategory } from '../types';

const basics: ShaderCategory = {
  id: 'basics',
  title: 'Shader Basics',
  titleZh: 'Shader 基础',
  description: 'From colors and shapes to noise, fractals, and lighting — the building blocks of fragment shaders.',
  descriptionZh: '从色彩、形状到噪声、分形和光照——片元着色器的构建基石。',
  tone: 'dark',
  cardType: 'shader',
  series: [
    {
      id: 'colors',
      title: 'Colors & Gradients',
      titleZh: '色彩与渐变',
      description: 'Fundamental color operations: HSB color space, smooth mixing, and smoothstep transitions.',
      descriptionZh: '色彩基础操作：HSB 色彩空间、平滑混合与 smoothstep 过渡。',
      demos: [
        {
          id: 'hsb-spectrum', title: 'HSB Color Spectrum', titleZh: 'HSB 色谱环',
          description: 'Visualizes the HSB color space. Hue varies horizontally, brightness vertically.',
          descriptionZh: '直观展示 HSB 色彩空间。色相沿水平方向变化，亮度沿垂直方向变化。',
          source: 'basics/colors/01-hsb-spectrum.glsl', params: [], presets: [],
        },
        {
          id: 'gradient-ring', title: 'Gradient Ring', titleZh: '渐变光环',
          description: 'A dynamic circular gradient using trigonometric palette functions.',
          descriptionZh: '使用三角函数调色板生成动态环形渐变。',
          source: 'basics/colors/02-gradient-ring.glsl',
          params: [{ name: 'u_speed', label: 'Speed', labelZh: '速度', min: 0, max: 5, step: 0.1, default: 1.0 }],
          presets: [{ name: 'slow', nameZh: '慢速', values: { u_speed: 0.3 } }, { name: 'normal', nameZh: '正常', values: { u_speed: 1.0 } }, { name: 'fast', nameZh: '快速', values: { u_speed: 3.0 } }],
        },
        {
          id: 'mix-smoothstep', title: 'mix() vs smoothstep()', titleZh: 'mix 与 smoothstep 对比',
          description: 'Side-by-side comparison of linear mix and smooth Hermite interpolation.',
          descriptionZh: '直观对比线性 mix 和平滑 smoothstep（Hermite 插值）的差异。',
          source: 'basics/colors/03-mix-smoothstep.glsl',
          params: [{ name: 'u_transition', label: 'Transition', labelZh: '过渡位置', min: 0, max: 1, step: 0.01, default: 0.5 }],
          presets: [{ name: 'left', nameZh: '偏左', values: { u_transition: 0.25 } }, { name: 'center', nameZh: '居中', values: { u_transition: 0.5 } }, { name: 'right', nameZh: '偏右', values: { u_transition: 0.75 } }],
        },
      ],
    },
    {
      id: 'shapes',
      title: 'Shape Drawing with SDF',
      titleZh: 'SDF 形状绘制',
      description: 'Signed Distance Functions for drawing sharp, resolution-independent 2D shapes.',
      descriptionZh: '使用有符号距离函数（SDF）绘制与分辨率无关的精确 2D 形状。',
      demos: [
        { id: 'sdf-basics', title: 'SDF Shape Gallery', titleZh: 'SDF 形状画廊', description: 'Circle, rectangle, triangle, and star rendered via signed distance functions.', descriptionZh: '通过有符号距离函数渲染圆形、矩形、三角形和星形。', source: 'basics/shapes/01-sdf-basics.glsl', params: [], presets: [] },
        {
          id: 'heart-sdf', title: 'Heart Shape', titleZh: '爱心 SDF',
          description: 'A beating heart rendered with a custom SDF. Adjust smoothness to see edge softening.',
          descriptionZh: '用自定义 SDF 渲染一颗跳动的心。调节平滑度观察边缘柔化效果。',
          source: 'basics/shapes/02-heart-sdf.glsl',
          params: [{ name: 'u_smooth', label: 'Smooth', labelZh: '平滑度', min: 0.1, max: 3.0, step: 0.1, default: 1.0 }],
          presets: [{ name: 'sharp', nameZh: '锐利', values: { u_smooth: 0.2 } }, { name: 'normal', nameZh: '标准', values: { u_smooth: 1.0 } }, { name: 'soft', nameZh: '柔和', values: { u_smooth: 2.5 } }],
        },
        {
          id: 'hexagon-ring', title: 'Hexagonal Rings', titleZh: '六边形环',
          description: 'Concentric hexagonal rings using polar coordinates with hexagonal SDF.',
          descriptionZh: '使用极坐标配合六边形 SDF 生成同心环状图案。',
          source: 'basics/shapes/03-hexagon-ring.glsl',
          params: [{ name: 'u_rings', label: 'Rings', labelZh: '环数', min: 4, max: 24, step: 1, default: 12 }, { name: 'u_scale', label: 'Scale', labelZh: '缩放', min: 1, max: 5, step: 0.1, default: 2.5 }],
          presets: [{ name: 'sparse', nameZh: '稀疏', values: { u_rings: 6, u_scale: 2.0 } }, { name: 'dense', nameZh: '密集', values: { u_rings: 18, u_scale: 3.5 } }],
        },
      ],
    },
    {
      id: 'patterns',
      title: 'Patterns & Repetition',
      titleZh: '图案与重复',
      description: 'Creating repeating patterns using fract(), tiling, and mirror techniques.',
      descriptionZh: '使用 fract() 平铺、镜像等技术创建重复图案。',
      demos: [
        {
          id: 'kaleidoscope', title: 'Kaleidoscope', titleZh: '万花筒',
          description: 'Angular mirroring creates symmetric kaleidoscopic patterns.',
          descriptionZh: '通过角度镜像创建对称的万花筒图案。',
          source: 'basics/patterns/01-kaleidoscope.glsl',
          params: [{ name: 'u_slices', label: 'Slices', labelZh: '切片数', min: 2, max: 24, step: 1, default: 8 }],
          presets: [{ name: 'four', nameZh: '四瓣', values: { u_slices: 4 } }, { name: 'eight', nameZh: '八瓣', values: { u_slices: 8 } }, { name: 'sixteen', nameZh: '十六瓣', values: { u_slices: 16 } }],
        },
        {
          id: 'artful-tiles', title: 'Tile Patterns', titleZh: '平铺图案',
          description: 'Repeating geometric tiles with rotation and morphing sub-elements.',
          descriptionZh: '重复几何平铺，子元素可旋转和变形。',
          source: 'basics/patterns/02-artful-tiles.glsl',
          params: [{ name: 'u_density', label: 'Density', labelZh: '密度', min: 2, max: 12, step: 1, default: 5 }],
          presets: [{ name: 'sparse', nameZh: '稀疏', values: { u_density: 3 } }, { name: 'medium', nameZh: '中等', values: { u_density: 5 } }, { name: 'dense', nameZh: '密集', values: { u_density: 8 } }],
        },
        {
          id: 'moire', title: 'Moire Patterns', titleZh: '摩尔纹',
          description: 'Interference patterns from overlapping radial wave systems.',
          descriptionZh: '两组径向波纹叠加产生的干涉图案。',
          source: 'basics/patterns/03-moire.glsl',
          params: [{ name: 'u_freq', label: 'Frequency', labelZh: '频率', min: 5, max: 40, step: 1, default: 15 }],
          presets: [{ name: 'low', nameZh: '低频', values: { u_freq: 8 } }, { name: 'mid', nameZh: '中频', values: { u_freq: 15 } }, { name: 'high', nameZh: '高频', values: { u_freq: 30 } }],
        },
      ],
    },
    {
      id: 'noise',
      title: 'Noise Functions',
      titleZh: '噪声函数',
      description: 'From basic value noise to fractal Brownian motion and domain warping.',
      descriptionZh: '从基础值噪声到分形布朗运动（fBM）和域扭曲。',
      demos: [
        {
          id: 'value-noise', title: 'Value Noise & fBM', titleZh: '值噪声与 fBM',
          description: 'Smooth value noise with multiple octaves for natural-looking textures.',
          descriptionZh: '多倍频程的平滑值噪声，产生自然的地形纹理。',
          source: 'basics/noise/01-value-noise.glsl',
          params: [{ name: 'u_scale', label: 'Scale', labelZh: '缩放', min: 1, max: 8, step: 0.1, default: 3.0 }, { name: 'u_octaves', label: 'Octaves', labelZh: '倍频', min: 1, max: 6, step: 1, default: 4 }],
          presets: [{ name: 'smooth', nameZh: '平滑', values: { u_scale: 2.0, u_octaves: 2 } }, { name: 'detail', nameZh: '细节', values: { u_scale: 4.0, u_octaves: 5 } }],
        },
        {
          id: 'clouds', title: 'Procedural Clouds', titleZh: '程序化云层',
          description: 'Cloud-like patterns using fBM noise with thresholding for fluffy shapes.',
          descriptionZh: '使用 fBM 噪声配合阈值生成蓬松的云层效果。',
          source: 'basics/noise/02-clouds.glsl',
          params: [{ name: 'u_coverage', label: 'Coverage', labelZh: '云量', min: -0.2, max: 0.6, step: 0.01, default: 0.1 }],
          presets: [{ name: 'clear', nameZh: '晴朗', values: { u_coverage: -0.1 } }, { name: 'partly', nameZh: '多云', values: { u_coverage: 0.2 } }, { name: 'overcast', nameZh: '阴天', values: { u_coverage: 0.45 } }],
        },
        {
          id: 'domain-warp', title: 'Domain Warping', titleZh: '域扭曲',
          description: 'Feeding noise into itself creates organic, flowing abstract textures.',
          descriptionZh: '将噪声的输出作为坐标偏移再次输入噪声，产生有机流动的抽象纹理。',
          source: 'basics/noise/03-domain-warp.glsl',
          params: [{ name: 'u_warp', label: 'Warp Amount', labelZh: '扭曲量', min: 0, max: 3, step: 0.1, default: 1.5 }],
          presets: [{ name: 'gentle', nameZh: '轻微', values: { u_warp: 0.5 } }, { name: 'medium', nameZh: '中等', values: { u_warp: 1.5 } }, { name: 'extreme', nameZh: '极度', values: { u_warp: 2.8 } }],
        },
      ],
    },
    {
      id: 'fractals',
      title: 'Fractals & Recursion',
      titleZh: '分形与递归',
      description: 'Classic fractal sets: Mandelbrot, Julia, and iterated function systems.',
      descriptionZh: '经典分形集合：Mandelbrot 集、Julia 集和迭代函数系统。',
      demos: [
        {
          id: 'mandelbrot', title: 'Mandelbrot Set', titleZh: 'Mandelbrot 集合',
          description: 'The iconic fractal. Zoom in to discover infinite self-similar detail.',
          descriptionZh: '经典分形图案。放大探索无限的细节。',
          source: 'basics/fractals/01-mandelbrot.glsl',
          params: [{ name: 'u_zoom', label: 'Zoom', labelZh: '缩放', min: 0.5, max: 20, step: 0.1, default: 1.0 }],
          presets: [{ name: 'full', nameZh: '全景', values: { u_zoom: 1.0 } }, { name: 'zoom1', nameZh: '放大', values: { u_zoom: 5.0 } }, { name: 'deep', nameZh: '深度', values: { u_zoom: 15.0 } }],
        },
        {
          id: 'julia', title: 'Julia Set Explorer', titleZh: 'Julia 集探索',
          description: 'Julia sets with interactive C parameter. Each C value produces a unique fractal.',
          descriptionZh: '可调节 C 参数的 Julia 集，每个 C 值都会产生独特的分形。',
          source: 'basics/fractals/02-julia.glsl',
          params: [{ name: 'u_cx', label: 'C Real', labelZh: 'C 实部', min: -1, max: 1, step: 0.01, default: -0.7 }, { name: 'u_cy', label: 'C Imag', labelZh: 'C 虚部', min: -1, max: 1, step: 0.01, default: 0.27 }],
          presets: [{ name: 'spiral', nameZh: '螺旋', values: { u_cx: -0.7, u_cy: 0.27 } }, { name: 'dendrite', nameZh: '树枝', values: { u_cx: 0.285, u_cy: 0.01 } }, { name: 'dragon', nameZh: '龙形', values: { u_cx: -0.4, u_cy: 0.6 } }],
        },
        {
          id: 'ifs-fractal', title: 'Iterated Function System', titleZh: '迭代函数系统',
          description: 'Recursive folding transform that creates intricate geometric fractals.',
          descriptionZh: '通过递归折叠变换生成复杂的几何分形图案。',
          source: 'basics/fractals/03-ifs-fractal.glsl',
          params: [{ name: 'u_iterations', label: 'Iterations', labelZh: '迭代次数', min: 1, max: 10, step: 1, default: 5 }],
          presets: [{ name: 'low', nameZh: '浅层', values: { u_iterations: 3 } }, { name: 'mid', nameZh: '中层', values: { u_iterations: 6 } }, { name: 'deep', nameZh: '深层', values: { u_iterations: 9 } }],
        },
      ],
    },
    {
      id: 'lighting',
      title: 'Lighting & Materials',
      titleZh: '光照与材质',
      description: 'Simulating 3D lighting on 2D surfaces: diffuse, specular, Fresnel, and metallics.',
      descriptionZh: '在 2D 平面上模拟 3D 光照：漫反射、镜面反射、菲涅尔效应与金属材质。',
      demos: [
        {
          id: 'lit-sphere', title: 'Lit Sphere', titleZh: '光照球体',
          description: 'Diffuse + specular + Fresnel rim lighting on a sphere, all in a fragment shader.',
          descriptionZh: '纯片元着色器实现的漫反射 + 镜面 + 菲涅尔边缘光球体。',
          source: 'basics/lighting/01-lit-sphere.glsl',
          params: [{ name: 'u_roughness', label: 'Roughness', labelZh: '粗糙度', min: 0, max: 1, step: 0.01, default: 0.3 }],
          presets: [{ name: 'glossy', nameZh: '光滑', values: { u_roughness: 0.1 } }, { name: 'matte', nameZh: '哑光', values: { u_roughness: 0.6 } }, { name: 'rough', nameZh: '粗糙', values: { u_roughness: 0.9 } }],
        },
        {
          id: 'metallic', title: 'Metallic Shading', titleZh: '金属着色',
          description: 'Metallic reflection model with configurable metalness from diffuse to mirror.',
          descriptionZh: '可调节金属度的反射模型，从漫反射到镜面反射连续过渡。',
          source: 'basics/lighting/02-metallic.glsl',
          params: [{ name: 'u_metalness', label: 'Metalness', labelZh: '金属度', min: 0, max: 1, step: 0.01, default: 0.7 }],
          presets: [{ name: 'plastic', nameZh: '塑料', values: { u_metalness: 0.1 } }, { name: 'metallic', nameZh: '金属', values: { u_metalness: 0.7 } }, { name: 'mirror', nameZh: '镜面', values: { u_metalness: 1.0 } }],
        },
        {
          id: 'water-droplet', title: 'Water Droplet', titleZh: '水珠效果',
          description: 'A translucent droplet with specular highlights and subtle refraction hints.',
          descriptionZh: '半透明水珠，带有高光和微妙的折射暗示。',
          source: 'basics/lighting/03-water-droplet.glsl', params: [], presets: [],
        },
      ],
    },
    {
      id: 'coordinates',
      title: 'Coordinate Transformations',
      titleZh: '坐标变换',
      description: 'Polar coordinates, rotation matrices, dynamic scaling, and mirror folding.',
      descriptionZh: '极坐标、旋转矩阵、动态缩放和镜像折叠。',
      demos: [
        {
          id: 'polar-flower', title: 'Polar Flower', titleZh: '极坐标之花',
          description: 'Flower-like patterns created by combining polar coordinates with cosine petals.',
          descriptionZh: '通过极坐标结合余弦花瓣函数创建花朵图案。',
          source: 'basics/coordinates/01-polar-flower.glsl',
          params: [{ name: 'u_petals', label: 'Petals', labelZh: '花瓣数', min: 2, max: 16, step: 1, default: 6 }, { name: 'u_twist', label: 'Twist', labelZh: '扭曲', min: 0, max: 3, step: 0.1, default: 1.0 }],
          presets: [{ name: 'rose', nameZh: '玫瑰', values: { u_petals: 5, u_twist: 0.5 } }, { name: 'daisy', nameZh: '雏菊', values: { u_petals: 8, u_twist: 1.5 } }, { name: 'lotus', nameZh: '莲花', values: { u_petals: 12, u_twist: 2.5 } }],
        },
        {
          id: 'rotation-mirror', title: 'Rotation & Mirror', titleZh: '旋转与镜像',
          description: 'Combined rotation and radial mirror folding for mandala-like symmetry.',
          descriptionZh: '旋转变换结合径向镜像折叠，生成曼陀罗式的对称图案。',
          source: 'basics/coordinates/02-rotation-mirror.glsl',
          params: [{ name: 'u_angle', label: 'Angle', labelZh: '旋转角度', min: 0, max: 1, step: 0.01, default: 0.25 }, { name: 'u_mirrors', label: 'Mirrors', labelZh: '镜面数', min: 2, max: 16, step: 1, default: 6 }],
          presets: [{ name: 'triangle', nameZh: '三角', values: { u_angle: 0.0, u_mirrors: 3 } }, { name: 'hexagon', nameZh: '六角', values: { u_angle: 0.25, u_mirrors: 6 } }, { name: 'mandala', nameZh: '曼陀罗', values: { u_angle: 0.5, u_mirrors: 12 } }],
        },
        {
          id: 'scale-tiling', title: 'Scale & Repeat', titleZh: '缩放与重复',
          description: 'Dynamic scaling combined with spatial repetition for rhythmic visual patterns.',
          descriptionZh: '动态缩放配合空间重复，产生有节奏的视觉图案。',
          source: 'basics/coordinates/03-scale-tiling.glsl',
          params: [{ name: 'u_scale', label: 'Scale', labelZh: '基础缩放', min: 1, max: 8, step: 0.1, default: 3.0 }, { name: 'u_bounce', label: 'Bounce', labelZh: '弹跳速度', min: 0, max: 3, step: 0.1, default: 1.0 }],
          presets: [{ name: 'still', nameZh: '静止', values: { u_scale: 4.0, u_bounce: 0.0 } }, { name: 'pulse', nameZh: '脉动', values: { u_scale: 3.0, u_bounce: 1.5 } }, { name: 'frantic', nameZh: '狂跳', values: { u_scale: 3.0, u_bounce: 2.5 } }],
        },
      ],
    },
  ],
};

registerCategory(basics);
