import { registerCategory } from '../registry';
import type { ShaderCategory } from '../types';

const effects: ShaderCategory = {
  id: 'effects',
  title: 'Interactive Effects',
  titleZh: '交互特效',
  description:
    'Real-time particle systems, fluid simulation, and organic cellular automata — all responding to your mouse.',
  descriptionZh: '实时粒子系统、流体模拟和有机元胞自动机——全部响应鼠标交互。',
  cardType: 'shader',
  series: [
    {
      id: 'particles',
      title: 'Particle Systems',
      titleZh: '粒子系统',
      description: 'Real-time particle simulations responding to mouse movement.',
      descriptionZh: '实时粒子模拟，响应鼠标移动。',
      demos: [
        {
          id: 'mouse-particles',
          title: 'Star Nebula Swarm',
          titleZh: '星云漩涡',
          description:
            'A multi-colored particle swarm that swirls around the cursor — attract or repel with trails that decay exponentially.',
          descriptionZh: '多彩粒子群绕光标旋转成星云漩涡——引力或斥力模式，拖尾指数衰减。',
          source: 'effects/particles/01-mouse-particles.glsl',
          params: [
            {
              name: 'u_particle_count',
              label: 'Particles',
              labelZh: '粒子数量',
              min: 0.2,
              max: 1,
              step: 0.05,
              default: 0.65,
            },
            {
              name: 'u_attract_repel',
              label: 'Attract / Repel',
              labelZh: '吸引 / 斥力',
              min: 0,
              max: 1,
              step: 0.01,
              default: 0.0,
            },
            {
              name: 'u_color_theme',
              label: 'Color Theme',
              labelZh: '色彩主题',
              min: 0,
              max: 1,
              step: 0.01,
              default: 0.0,
            },
            {
              name: 'u_trail_length',
              label: 'Trail Length',
              labelZh: '拖尾长度',
              min: 0,
              max: 1,
              step: 0.05,
              default: 0.5,
            },
          ],
          presets: [
            {
              name: 'nebula',
              nameZh: '星云',
              values: {
                u_particle_count: 0.85,
                u_attract_repel: 0.0,
                u_color_theme: 0.0,
                u_trail_length: 0.6,
              },
            },
            {
              name: 'ember',
              nameZh: '余烬',
              values: {
                u_particle_count: 0.4,
                u_attract_repel: 0.0,
                u_color_theme: 0.55,
                u_trail_length: 0.9,
              },
            },
            {
              name: 'repulse',
              nameZh: '斥力风暴',
              values: {
                u_particle_count: 0.65,
                u_attract_repel: 1.0,
                u_color_theme: 0.3,
                u_trail_length: 0.4,
              },
            },
          ],
          interactive: true,
        },
        {
          id: 'flow-field',
          title: 'Aurora Flow Field',
          titleZh: '极光流场',
          description:
            'Streamlines trace a Perlin vector field with a warm-to-cool gradient; the cursor bends the local currents into vortex rings.',
          descriptionZh: '流线沿柏林噪声矢量场蜿蜒，暖到冷渐变；光标将局部流场扭曲成漩涡环。',
          source: 'effects/particles/02-flow-field.glsl',
          params: [
            {
              name: 'u_density',
              label: 'Density',
              labelZh: '密度',
              min: 0.2,
              max: 1.5,
              step: 0.1,
              default: 0.8,
            },
            {
              name: 'u_noise_scale',
              label: 'Noise Scale',
              labelZh: '噪声尺度',
              min: 0.3,
              max: 3,
              step: 0.1,
              default: 1.2,
            },
            {
              name: 'u_flow_speed',
              label: 'Flow Speed',
              labelZh: '流速',
              min: 0.2,
              max: 3,
              step: 0.1,
              default: 1.0,
            },
            {
              name: 'u_color_theme',
              label: 'Color Theme',
              labelZh: '色彩主题',
              min: 0,
              max: 1,
              step: 0.01,
              default: 0.0,
            },
          ],
          presets: [
            {
              name: 'aurora',
              nameZh: '极光',
              values: { u_density: 1.0, u_noise_scale: 1.4, u_flow_speed: 1.2, u_color_theme: 0.0 },
            },
            {
              name: 'ocean',
              nameZh: '洋流',
              values: {
                u_density: 0.9,
                u_noise_scale: 0.6,
                u_flow_speed: 0.6,
                u_color_theme: 0.33,
              },
            },
            {
              name: 'magma',
              nameZh: '熔岩',
              values: {
                u_density: 1.2,
                u_noise_scale: 1.0,
                u_flow_speed: 2.2,
                u_color_theme: 0.66,
              },
            },
            {
              name: 'sakura',
              nameZh: '夜樱',
              values: {
                u_density: 0.55,
                u_noise_scale: 2.2,
                u_flow_speed: 0.8,
                u_color_theme: 1.0,
              },
            },
          ],
          interactive: true,
        },
      ],
    },
    {
      id: 'fluids',
      title: 'Fluid Simulation',
      titleZh: '流体模拟',
      description: 'Procedural ink diffusion and smoke-like effects.',
      descriptionZh: '程序化水墨扩散和烟雾效果。',
      demos: [
        {
          id: 'ink-diffusion',
          title: 'Sumi-e Ink Diffusion',
          titleZh: '水墨扩散',
          description:
            'Multi-colored ink drops spread through noise-perturbed Gaussian kernels over textured rice paper; move the cursor to paint with ink.',
          descriptionZh: '多色墨滴在宣纸纹理上经噪声扰动的高斯核晕染扩散；移动光标以墨作画。',
          source: 'effects/fluids/01-ink-diffusion.glsl',
          params: [
            {
              name: 'u_viscosity',
              label: 'Viscosity',
              labelZh: '粘稠度',
              min: 0.2,
              max: 2.5,
              step: 0.1,
              default: 1.0,
            },
            {
              name: 'u_ink_color',
              label: 'Ink Color',
              labelZh: '墨色',
              type: 'color',
              defaultColor: [0.05, 0.05, 0.05],
            },
            {
              name: 'u_drop_spread',
              label: 'Drop Spread',
              labelZh: '扩散范围',
              min: 0.2,
              max: 2,
              step: 0.05,
              default: 1.0,
            },
            {
              name: 'u_paper_texture',
              label: 'Paper Texture',
              labelZh: '纸纹强度',
              min: 0,
              max: 1,
              step: 0.05,
              default: 0.5,
            },
          ],
          presets: [
            {
              name: 'sumi',
              nameZh: '墨黑',
              values: {
                u_viscosity: 1.2,
                u_ink_color: [0.04, 0.04, 0.045],
                u_drop_spread: 0.9,
                u_paper_texture: 0.7,
              },
            },
            {
              name: 'cyan',
              nameZh: '青蓝',
              values: {
                u_viscosity: 0.8,
                u_ink_color: [0.1, 0.45, 0.75],
                u_drop_spread: 1.2,
                u_paper_texture: 0.5,
              },
            },
            {
              name: 'vermillion',
              nameZh: '朱砂',
              values: {
                u_viscosity: 1.0,
                u_ink_color: [0.85, 0.18, 0.12],
                u_drop_spread: 1.0,
                u_paper_texture: 0.55,
              },
            },
          ],
          interactive: true,
        },
      ],
    },
    {
      id: 'organic',
      title: 'Organic Life',
      titleZh: '有机生命',
      description: 'Cellular automata and growth patterns.',
      descriptionZh: '元胞自动机和生长模式。',
      demos: [
        {
          id: 'game-of-life',
          title: 'Ecosystem Evolution',
          titleZh: '生态演化',
          description:
            'Three species of cells evolve under different survival rules — paint life with the cursor, and click-pulses seed expanding waves.',
          descriptionZh: '三种物种按不同存活规则共同演化——光标涂抹生命，脉冲波环播种扩散。',
          source: 'effects/organic/01-game-of-life.glsl',
          params: [
            {
              name: 'u_grid_scale',
              label: 'Grid Scale',
              labelZh: '网格大小',
              min: 0.3,
              max: 2,
              step: 0.1,
              default: 1.0,
            },
            {
              name: 'u_evolution_speed',
              label: 'Evolution Speed',
              labelZh: '演化速度',
              min: 0.2,
              max: 3,
              step: 0.1,
              default: 1.0,
            },
            {
              name: 'u_species_colors',
              label: 'Species Colors',
              labelZh: '物种配色',
              min: 0,
              max: 1,
              step: 0.01,
              default: 0.0,
            },
          ],
          presets: [
            {
              name: 'forest',
              nameZh: '森林',
              values: { u_grid_scale: 1.1, u_evolution_speed: 0.7, u_species_colors: 0.0 },
            },
            {
              name: 'ocean',
              nameZh: '海洋',
              values: { u_grid_scale: 0.8, u_evolution_speed: 1.3, u_species_colors: 0.5 },
            },
            {
              name: 'alien',
              nameZh: '异星',
              values: { u_grid_scale: 1.4, u_evolution_speed: 2.0, u_species_colors: 1.0 },
            },
          ],
          interactive: true,
        },
      ],
    },
    {
      id: 'reaction',
      title: 'Reaction-Diffusion',
      titleZh: '反应扩散系统',
      description: 'Gray-Scott model producing coral, zebra stripes, and leopard spots.',
      descriptionZh: 'Gray-Scott 模型，产生珊瑚、斑马纹和豹斑等有机图案。',
      demos: [
        {
          id: 'reaction-diffusion',
          title: 'Reaction-Diffusion Patterns',
          titleZh: '反应扩散图案',
          description: 'Organic Turing patterns — inject chemical perturbations with the mouse.',
          descriptionZh: '有机图灵图案——鼠标注入化学扰动。',
          source: 'effects/reaction/01-reaction-diffusion.glsl',
          params: [
            {
              name: 'u_feed_rate',
              label: 'Feed Rate',
              labelZh: '供给率',
              min: 0.01,
              max: 0.1,
              step: 0.002,
              default: 0.055,
            },
            {
              name: 'u_kill_rate',
              label: 'Kill Rate',
              labelZh: '消耗率',
              min: 0.03,
              max: 0.08,
              step: 0.001,
              default: 0.062,
            },
            {
              name: 'u_diffusion_speed',
              label: 'Diffusion',
              labelZh: '扩散速度',
              min: 0.5,
              max: 3,
              step: 0.1,
              default: 1.5,
            },
          ],
          presets: [
            {
              name: 'coral',
              nameZh: '珊瑚',
              values: { u_feed_rate: 0.055, u_kill_rate: 0.062, u_diffusion_speed: 1.5 },
            },
            {
              name: 'zebra',
              nameZh: '斑马',
              values: { u_feed_rate: 0.035, u_kill_rate: 0.065, u_diffusion_speed: 2.0 },
            },
            {
              name: 'spots',
              nameZh: '豹纹',
              values: { u_feed_rate: 0.04, u_kill_rate: 0.06, u_diffusion_speed: 1.0 },
            },
          ],
          interactive: true,
        },
        {
          id: 'fractal-flame',
          title: 'Fractal Flame',
          titleZh: '分形火焰',
          description: 'Multi-layer fractal noise flame with heat shimmer and wind-driven smoke.',
          descriptionZh: '多层分形噪声火焰，带热浪扭曲和风驱烟尘。',
          source: 'effects/reaction/02-fractal-flame.glsl',
          params: [
            {
              name: 'u_flame_height',
              label: 'Height',
              labelZh: '火焰高度',
              min: 0.3,
              max: 1.2,
              step: 0.02,
              default: 0.7,
            },
            {
              name: 'u_turbulence',
              label: 'Turbulence',
              labelZh: '湍流',
              min: 0.2,
              max: 2,
              step: 0.05,
              default: 1.0,
            },
            {
              name: 'u_smoke_amount',
              label: 'Smoke',
              labelZh: '烟雾',
              min: 0,
              max: 1.5,
              step: 0.05,
              default: 0.4,
            },
            {
              name: 'u_wind',
              label: 'Wind',
              labelZh: '风',
              min: -0.5,
              max: 0.5,
              step: 0.02,
              default: 0.0,
            },
          ],
          presets: [
            {
              name: 'candle',
              nameZh: '烛火',
              values: { u_flame_height: 0.4, u_turbulence: 0.5, u_smoke_amount: 0.1, u_wind: 0.0 },
            },
            {
              name: 'campfire',
              nameZh: '篝火',
              values: { u_flame_height: 0.7, u_turbulence: 1.0, u_smoke_amount: 0.4, u_wind: 0.0 },
            },
            {
              name: 'inferno',
              nameZh: '烈焰',
              values: { u_flame_height: 1.0, u_turbulence: 1.8, u_smoke_amount: 0.8, u_wind: 0.1 },
            },
          ],
          interactive: true,
        },
      ],
    },
  ],
};

registerCategory(effects);
