import { registerCategory } from '../registry';
import type { ShaderCategory } from '../types';

const filters: ShaderCategory = {
  id: 'filters',
  title: 'Camera Filters',
  titleZh: '镜头滤镜',
  description:
    'Real-time webcam filters — from classic monochrome to edge detection, halftone, glitch, and kaleidoscope.',
  descriptionZh: '实时摄像头滤镜——从经典黑白到边缘检测、半色调、故障艺术和万花筒。',
  cardType: 'filter',
  series: [
    {
      id: 'classic',
      title: 'Classic Photo Filters',
      titleZh: '经典摄影滤镜',
      description: 'Grayscale, sepia, and color grading effects for your webcam feed.',
      descriptionZh: '黑白、老照片和色彩分级等实时摄像头效果。',
      demos: [
        {
          id: 'grayscale',
          title: 'Professional B&W',
          titleZh: '专业黑白',
          description:
            'Weighted luminance conversion with an S-curve contrast stage, film grain, and vignette — a darkroom-quality monochrome look.',
          descriptionZh:
            '可调通道权重灰度转换，叠加 S 曲线对比度、胶片颗粒与暗角——暗房级黑白质感。',
          source: 'filters/classic/01-grayscale.glsl',
          params: [
            {
              name: 'u_red_weight',
              label: 'Red',
              labelZh: '红色权重',
              min: 0,
              max: 1,
              step: 0.01,
              default: 0.299,
            },
            {
              name: 'u_green_weight',
              label: 'Green',
              labelZh: '绿色权重',
              min: 0,
              max: 1,
              step: 0.01,
              default: 0.587,
            },
            {
              name: 'u_blue_weight',
              label: 'Blue',
              labelZh: '蓝色权重',
              min: 0,
              max: 1,
              step: 0.01,
              default: 0.114,
            },
            {
              name: 'u_contrast',
              label: 'Contrast',
              labelZh: '对比度',
              min: 0,
              max: 1.5,
              step: 0.05,
              default: 0.35,
            },
            {
              name: 'u_grain',
              label: 'Grain',
              labelZh: '颗粒',
              min: 0,
              max: 1,
              step: 0.05,
              default: 0.35,
            },
            {
              name: 'u_vignette',
              label: 'Vignette',
              labelZh: '暗角',
              min: 0,
              max: 1,
              step: 0.05,
              default: 0.4,
            },
          ],
          presets: [
            {
              name: 'purity',
              nameZh: '纯净',
              values: {
                u_red_weight: 0.299,
                u_green_weight: 0.587,
                u_blue_weight: 0.114,
                u_contrast: 0.2,
                u_grain: 0.15,
                u_vignette: 0.25,
              },
            },
            {
              name: 'fine-art',
              nameZh: '艺术胶片',
              values: {
                u_red_weight: 0.299,
                u_green_weight: 0.587,
                u_blue_weight: 0.114,
                u_contrast: 0.6,
                u_grain: 0.55,
                u_vignette: 0.5,
              },
            },
            {
              name: 'noir',
              nameZh: '黑色电影',
              values: {
                u_red_weight: 0.55,
                u_green_weight: 0.35,
                u_blue_weight: 0.1,
                u_contrast: 1.1,
                u_grain: 0.4,
                u_vignette: 0.8,
              },
            },
          ],
        },
        {
          id: 'sepia',
          title: 'Time Capsule',
          titleZh: '时光胶囊',
          description:
            'Full sepia matrix with drifting grain, vertical film scratches, a warm light leak, and faded corners for a true vintage print.',
          descriptionZh:
            '完整 sepia 矩阵变换，叠加漂移颗粒、垂直胶片划痕、暖色漏光和褪色边角——真正的旧照片质感。',
          source: 'filters/classic/02-sepia.glsl',
          params: [
            {
              name: 'u_strength',
              label: 'Strength',
              labelZh: '强度',
              min: 0,
              max: 1,
              step: 0.01,
              default: 0.8,
            },
            {
              name: 'u_grain',
              label: 'Grain',
              labelZh: '颗粒',
              min: 0,
              max: 1,
              step: 0.05,
              default: 0.3,
            },
            {
              name: 'u_vignette',
              label: 'Vignette',
              labelZh: '暗角',
              min: 0,
              max: 1,
              step: 0.05,
              default: 0.5,
            },
            {
              name: 'u_scratch_amount',
              label: 'Scratches',
              labelZh: '划痕',
              min: 0,
              max: 1,
              step: 0.05,
              default: 0.5,
            },
          ],
          presets: [
            {
              name: 'gentle',
              nameZh: '淡雅',
              values: { u_strength: 0.35, u_grain: 0.1, u_vignette: 0.3, u_scratch_amount: 0.15 },
            },
            {
              name: 'vintage',
              nameZh: '经典怀旧',
              values: { u_strength: 0.7, u_grain: 0.3, u_vignette: 0.5, u_scratch_amount: 0.45 },
            },
            {
              name: 'timecapsule',
              nameZh: '时光胶囊',
              values: { u_strength: 1.0, u_grain: 0.6, u_vignette: 0.75, u_scratch_amount: 0.9 },
            },
          ],
        },
      ],
    },
    {
      id: 'artistic',
      title: 'Artistic Style',
      titleZh: '艺术风格化',
      description: 'Edge detection, halftone, and other artistic rendering techniques.',
      descriptionZh: '边缘检测、半色调网点等艺术渲染技法。',
      demos: [
        {
          id: 'edge-detect',
          title: 'Multi-Style Edge Draw',
          titleZh: '多风格边缘绘画',
          description:
            'Sobel edge detection rendered as pencil sketch, ink line, neon tube, or chalk on slate — with a selectable line color.',
          descriptionZh:
            'Sobel 边缘检测，支持铅笔素描、钢笔墨水、霓虹灯管、粉笔板四种画风，线条颜色可自定义。',
          source: 'filters/artistic/01-edge-detect.glsl',
          params: [
            {
              name: 'u_style',
              label: 'Style',
              labelZh: '风格',
              min: 0,
              max: 3,
              step: 1,
              default: 0,
            },
            {
              name: 'u_threshold',
              label: 'Threshold',
              labelZh: '阈值',
              min: 0.05,
              max: 0.5,
              step: 0.005,
              default: 0.15,
            },
            {
              name: 'u_line_color',
              label: 'Line Color',
              labelZh: '线条颜色',
              type: 'color',
              defaultColor: [0.08, 0.08, 0.1],
            },
            {
              name: 'u_bg_alpha',
              label: 'Paper BG',
              labelZh: '纸面背景',
              min: 0,
              max: 1,
              step: 0.05,
              default: 1,
            },
          ],
          presets: [
            {
              name: 'pencil',
              nameZh: '铅笔素描',
              values: {
                u_style: 0,
                u_threshold: 0.12,
                u_line_color: [0.05, 0.05, 0.07],
                u_bg_alpha: 1,
              },
            },
            {
              name: 'ink',
              nameZh: '钢笔墨水',
              values: {
                u_style: 1,
                u_threshold: 0.15,
                u_line_color: [0.03, 0.03, 0.04],
                u_bg_alpha: 1,
              },
            },
            {
              name: 'neon',
              nameZh: '霓虹灯管',
              values: {
                u_style: 2,
                u_threshold: 0.12,
                u_line_color: [0.25, 0.95, 1.0],
                u_bg_alpha: 0,
              },
            },
            {
              name: 'chalk',
              nameZh: '粉笔',
              values: {
                u_style: 3,
                u_threshold: 0.18,
                u_line_color: [0.95, 0.92, 0.82],
                u_bg_alpha: 0.5,
              },
            },
          ],
        },
        {
          id: 'halftone',
          title: 'CMYK Halftone',
          titleZh: 'CMYK 半色调',
          description:
            'Four-color screen printing with rotated CMYK dot plates, shape switching (dot / diamond / line), and a paper fiber surface.',
          descriptionZh:
            '四色套印半色调，CMYK 各用独立网角，支持圆点/菱形/线条网点切换和纸张纤维质感。',
          source: 'filters/artistic/02-halftone.glsl',
          params: [
            {
              name: 'u_dot_size',
              label: 'Dot Size',
              labelZh: '网点大小',
              min: 0.5,
              max: 4,
              step: 0.1,
              default: 1.2,
            },
            {
              name: 'u_angle',
              label: 'Angle',
              labelZh: '网角',
              min: -45,
              max: 45,
              step: 1,
              default: 0,
            },
            {
              name: 'u_dot_shape',
              label: 'Dot Shape',
              labelZh: '网点形状',
              min: 0,
              max: 2,
              step: 1,
              default: 0,
            },
            {
              name: 'u_paper_color',
              label: 'Paper',
              labelZh: '纸色',
              type: 'color',
              defaultColor: [0.96, 0.94, 0.89],
            },
          ],
          presets: [
            {
              name: 'newsprint',
              nameZh: '报纸印刷',
              values: {
                u_dot_size: 0.8,
                u_angle: 0,
                u_dot_shape: 0,
                u_paper_color: [0.95, 0.93, 0.88],
              },
            },
            {
              name: 'comic',
              nameZh: '漫画网点',
              values: {
                u_dot_size: 1.6,
                u_angle: 8,
                u_dot_shape: 1,
                u_paper_color: [0.97, 0.95, 0.9],
              },
            },
            {
              name: 'silkscreen',
              nameZh: '丝网印刷',
              values: {
                u_dot_size: 2.4,
                u_angle: 0,
                u_dot_shape: 2,
                u_paper_color: [0.92, 0.89, 0.84],
              },
            },
          ],
        },
      ],
    },
    {
      id: 'distortion',
      title: 'Distortion Effects',
      titleZh: '变形扭曲',
      description: 'Kaleidoscope mirrors and glitch art effects for creative video manipulation.',
      descriptionZh: '万花筒镜像和故障艺术效果，创意视频变形。',
      demos: [
        {
          id: 'kaleidoscope',
          title: 'Pro Kaleidoscope',
          titleZh: '专业万花筒',
          description:
            'Polar folding with three mirror modes (reflect / rotate / butterfly), soft wedge seams, and color boost for a jewel-like image.',
          descriptionZh:
            '极坐标折叠，三种镜像模式（反射/旋转/蝶翼）可选，楔形边缘柔化并增强色彩饱和度。',
          source: 'filters/distortion/01-kaleidoscope.glsl',
          params: [
            {
              name: 'u_slices',
              label: 'Slices',
              labelZh: '切片数',
              min: 2,
              max: 20,
              step: 1,
              default: 8,
            },
            {
              name: 'u_rotation',
              label: 'Rotation',
              labelZh: '旋转',
              min: 0,
              max: 6.28,
              step: 0.05,
              default: 0.0,
            },
            {
              name: 'u_saturation',
              label: 'Saturation',
              labelZh: '饱和度',
              min: 0,
              max: 1.5,
              step: 0.05,
              default: 0.5,
            },
            {
              name: 'u_mirror_mode',
              label: 'Mirror Mode',
              labelZh: '镜像模式',
              min: 0,
              max: 2,
              step: 1,
              default: 0,
            },
          ],
          presets: [
            {
              name: 'mandala',
              nameZh: '曼陀罗',
              values: { u_slices: 8, u_rotation: 0.0, u_saturation: 0.4, u_mirror_mode: 0 },
            },
            {
              name: 'gyroscope',
              nameZh: '旋转镜',
              values: { u_slices: 6, u_rotation: 0.4, u_saturation: 0.6, u_mirror_mode: 1 },
            },
            {
              name: 'butterfly',
              nameZh: '蝶翼',
              values: { u_slices: 4, u_rotation: 0.0, u_saturation: 0.7, u_mirror_mode: 2 },
            },
          ],
        },
        {
          id: 'glitch',
          title: 'Cyberpunk Glitch',
          titleZh: '赛博朋克故障',
          description:
            'Per-row RGB split, CRT scanlines, median pixel-sort rows, and a hue cycle drifting down the frame.',
          descriptionZh: '逐行 RGB 通道分离、CRT 扫描线、中值像素排序行和随画面下移的色相循环。',
          source: 'filters/distortion/02-glitch.glsl',
          params: [
            {
              name: 'u_intensity',
              label: 'Intensity',
              labelZh: '强度',
              min: 0,
              max: 2,
              step: 0.05,
              default: 0.7,
            },
            {
              name: 'u_scanline_amount',
              label: 'Scanlines',
              labelZh: '扫描线',
              min: 0,
              max: 2,
              step: 0.05,
              default: 0.8,
            },
            {
              name: 'u_hue_shift',
              label: 'Hue Shift',
              labelZh: '色相偏移',
              min: 0,
              max: 1.5,
              step: 0.05,
              default: 0.15,
            },
            {
              name: 'u_glitch_density',
              label: 'Glitch Density',
              labelZh: '故障密度',
              min: 0.1,
              max: 1,
              step: 0.05,
              default: 0.5,
            },
          ],
          presets: [
            {
              name: 'subtle',
              nameZh: '轻微',
              values: {
                u_intensity: 0.3,
                u_scanline_amount: 0.5,
                u_hue_shift: 0.05,
                u_glitch_density: 0.3,
              },
            },
            {
              name: 'vhs',
              nameZh: 'VHS 录像',
              values: {
                u_intensity: 0.8,
                u_scanline_amount: 0.8,
                u_hue_shift: 0.15,
                u_glitch_density: 0.5,
              },
            },
            {
              name: 'cyberpunk',
              nameZh: '赛博朋克',
              values: {
                u_intensity: 1.8,
                u_scanline_amount: 1.5,
                u_hue_shift: 0.6,
                u_glitch_density: 0.9,
              },
            },
          ],
        },
      ],
    },
  ],
};

registerCategory(filters);
