import { registerCategory } from '../registry';
import type { ShaderCategory } from '../types';

const paintings: ShaderCategory = {
  id: 'paintings',
  title: 'Painting Recreations',
  titleZh: '名画重现',
  description: 'Iconic masterpieces reinterpreted as interactive procedural shaders.',
  descriptionZh: '用程序化着色器重新诠释经典名画——让世界名画动起来。',
  cardType: 'shader',
  series: [
    {
      id: 'impressionism',
      title: 'Impressionism',
      titleZh: '印象派系列',
      description:
        'Procedural brushstrokes and dynamic lighting bring Impressionist masterpieces to life.',
      descriptionZh: '程序化笔触与动态光影，让印象派名作活起来。',
      demos: [
        {
          id: 'starry-night',
          title: 'Starry Night — Van Gogh',
          titleZh: '星月夜 — 梵高',
          description: 'Swirling night sky with mouse-trailing meteor streaks and breathing stars.',
          descriptionZh: '旋转星空，鼠标划过产生流星拖尾，星星随光标呼吸明灭。',
          source: 'paintings/impressionism/01-starry-night.glsl',
          params: [
            {
              name: 'u_turbulence',
              label: 'Turbulence',
              labelZh: '湍流强度',
              min: 0.2,
              max: 3,
              step: 0.1,
              default: 1.5,
            },
            {
              name: 'u_star_brightness',
              label: 'Stars',
              labelZh: '星光亮度',
              min: 0.3,
              max: 2,
              step: 0.05,
              default: 1.0,
            },
            {
              name: 'u_color_shift',
              label: 'Color Shift',
              labelZh: '色调偏移',
              min: 0,
              max: 1,
              step: 0.01,
              default: 0.0,
            },
          ],
          presets: [
            {
              name: 'calm',
              nameZh: '平静',
              values: { u_turbulence: 0.5, u_star_brightness: 0.7, u_color_shift: 0.0 },
            },
            {
              name: 'classic',
              nameZh: '原版',
              values: { u_turbulence: 1.5, u_star_brightness: 1.0, u_color_shift: 0.15 },
            },
            {
              name: 'storm',
              nameZh: '风暴',
              values: { u_turbulence: 2.8, u_star_brightness: 1.8, u_color_shift: 0.3 },
            },
          ],
          interactive: true,
        },
        {
          id: 'water-lilies',
          title: 'Water Lilies — Monet',
          titleZh: '睡莲 — 莫奈',
          description:
            'Click the water to generate expanding ripples; lily pads drift with the waves.',
          descriptionZh: '点击水面产生涟漪扩散，睡莲叶片随波漂移。',
          source: 'paintings/impressionism/02-water-lilies.glsl',
          params: [
            {
              name: 'u_ripple',
              label: 'Ripple',
              labelZh: '波纹强度',
              min: 0,
              max: 3,
              step: 0.1,
              default: 1.0,
            },
            {
              name: 'u_splash_radius',
              label: 'Splash',
              labelZh: '溅射半径',
              min: 0.05,
              max: 0.4,
              step: 0.01,
              default: 0.15,
            },
            {
              name: 'u_petal_color',
              label: 'Petal',
              labelZh: '花瓣色调',
              type: 'color',
              defaultColor: [0.95, 0.75, 0.85],
            },
          ],
          presets: [
            {
              name: 'still',
              nameZh: '静止',
              values: { u_ripple: 0.2, u_splash_radius: 0.06, u_petal_color: [0.95, 0.85, 0.75] },
            },
            {
              name: 'gentle',
              nameZh: '微风',
              values: { u_ripple: 1.0, u_splash_radius: 0.15, u_petal_color: [0.95, 0.75, 0.85] },
            },
            {
              name: 'windy',
              nameZh: '有风',
              values: { u_ripple: 2.5, u_splash_radius: 0.3, u_petal_color: [1.0, 0.6, 0.7] },
            },
          ],
          interactive: true,
        },
        {
          id: 'impression-sunrise',
          title: 'Impression, Sunrise — Monet',
          titleZh: '日出·印象 — 莫奈',
          description: 'Mouse position controls the sun height and light angle in real-time.',
          descriptionZh: '鼠标位置控制太阳升降，光照角度实时变化。',
          source: 'paintings/impressionism/03-impression-sunrise.glsl',
          params: [
            {
              name: 'u_mist',
              label: 'Mist',
              labelZh: '雾气浓度',
              min: 0.3,
              max: 2.5,
              step: 0.1,
              default: 1.2,
            },
            {
              name: 'u_sun_angle',
              label: 'Sun Angle',
              labelZh: '太阳角度',
              min: 0,
              max: 1,
              step: 0.02,
              default: 0.5,
            },
            {
              name: 'u_glow_color',
              label: 'Glow',
              labelZh: '光晕色',
              type: 'color',
              defaultColor: [1.0, 0.7, 0.3],
            },
          ],
          presets: [
            {
              name: 'dawn',
              nameZh: '破晓',
              values: { u_mist: 1.5, u_sun_angle: 0.3, u_glow_color: [1.0, 0.5, 0.2] },
            },
            {
              name: 'morning',
              nameZh: '清晨',
              values: { u_mist: 1.0, u_sun_angle: 0.5, u_glow_color: [1.0, 0.7, 0.3] },
            },
            {
              name: 'noon',
              nameZh: '正午',
              values: { u_mist: 0.5, u_sun_angle: 0.8, u_glow_color: [1.0, 0.9, 0.6] },
            },
          ],
          interactive: true,
        },
      ],
    },
    {
      id: 'geometric',
      title: 'Geometric Abstraction',
      titleZh: '几何抽象系列',
      description:
        'Living geometry — Mondrian blocks drift and Kandinsky shapes dance with the cursor.',
      descriptionZh: '活的几何——蒙德里安色块游走，康定斯基图形随光标起舞。',
      demos: [
        {
          id: 'mondrian',
          title: 'Composition — Mondrian',
          titleZh: '红黄蓝构成 — 蒙德里安',
          description:
            'Primary-color rectangles slowly wander; drag the mouse to rebalance the composition.',
          descriptionZh: '三原色块随时间缓慢游走，鼠标拖拽重新平衡构图。',
          source: 'paintings/geometric/01-mondrian.glsl',
          params: [
            {
              name: 'u_wander_speed',
              label: 'Wander',
              labelZh: '游走速度',
              min: 0,
              max: 1.5,
              step: 0.05,
              default: 0.3,
            },
            {
              name: 'u_block_size',
              label: 'Block Size',
              labelZh: '色块大小',
              min: 0.7,
              max: 1.5,
              step: 0.02,
              default: 1.0,
            },
          ],
          presets: [
            { name: 'stable', nameZh: '稳定', values: { u_wander_speed: 0.1, u_block_size: 1.0 } },
            { name: 'drift', nameZh: '漂移', values: { u_wander_speed: 0.5, u_block_size: 1.0 } },
            { name: 'chaos', nameZh: '混沌', values: { u_wander_speed: 1.2, u_block_size: 1.3 } },
          ],
          interactive: true,
        },
        {
          id: 'kandinsky',
          title: 'Composition VIII — Kandinsky',
          titleZh: '构图 VIII — 康定斯基',
          description:
            'Circles and lines rotate and scale with mouse movement — a dynamic sculpture.',
          descriptionZh: '圆形和线条随鼠标旋转缩放——动态雕塑。',
          source: 'paintings/geometric/02-kandinsky.glsl',
          params: [
            {
              name: 'u_rotation',
              label: 'Rotation',
              labelZh: '旋转',
              min: -1,
              max: 1,
              step: 0.02,
              default: 0.0,
            },
            {
              name: 'u_shape_count',
              label: 'Density',
              labelZh: '图形密度',
              min: 5,
              max: 30,
              step: 1,
              default: 15,
            },
          ],
          presets: [
            { name: 'sparse', nameZh: '稀疏', values: { u_rotation: 0.2, u_shape_count: 8 } },
            { name: 'balanced', nameZh: '均衡', values: { u_rotation: 0.0, u_shape_count: 15 } },
            { name: 'dense', nameZh: '密集', values: { u_rotation: -0.3, u_shape_count: 25 } },
          ],
          interactive: true,
        },
      ],
    },
    {
      id: 'modern',
      title: 'Modern & Ukiyo-e',
      titleZh: '浮世绘与现代系列',
      description:
        'The Great Wave surges, Rothko breathes, and Pollock splatters — interactive modern art.',
      descriptionZh: '巨浪翻涌、色域呼吸、滴画泼溅——可交互的现代艺术。',
      demos: [
        {
          id: 'great-wave',
          title: 'The Great Wave — Hokusai',
          titleZh: '神奈川冲浪里 — 葛饰北斋',
          description:
            'Mouse movement whips up towering waves; foam density tracks cursor intensity.',
          descriptionZh: '鼠标移动掀起巨浪，浪花泡沫跟随光标强度变化。',
          source: 'paintings/modern/01-great-wave.glsl',
          params: [
            {
              name: 'u_wave_height',
              label: 'Wave',
              labelZh: '浪高',
              min: 0.5,
              max: 2.5,
              step: 0.1,
              default: 1.5,
            },
            {
              name: 'u_foam_density',
              label: 'Foam',
              labelZh: '泡沫密度',
              min: 0.1,
              max: 2,
              step: 0.05,
              default: 1.0,
            },
            {
              name: 'u_curl_sharpness',
              label: 'Sharpness',
              labelZh: '浪尖锐度',
              min: 0.5,
              max: 3,
              step: 0.1,
              default: 1.8,
            },
          ],
          presets: [
            {
              name: 'gentle',
              nameZh: '小浪',
              values: { u_wave_height: 0.8, u_foam_density: 0.4, u_curl_sharpness: 1.2 },
            },
            {
              name: 'classic',
              nameZh: '经典',
              values: { u_wave_height: 1.5, u_foam_density: 1.0, u_curl_sharpness: 1.8 },
            },
            {
              name: 'tsunami',
              nameZh: '巨浪',
              values: { u_wave_height: 2.3, u_foam_density: 1.8, u_curl_sharpness: 2.6 },
            },
          ],
          interactive: true,
        },
        {
          id: 'rothko',
          title: 'Color Fields — Rothko',
          titleZh: '色域画 — 罗斯科',
          description:
            'Color rectangles breathe (expand/contract) with mouse proximity; mood shifts with cursor.',
          descriptionZh: '色块随鼠标位置呼吸式膨胀收缩，情绪色调随光标变化。',
          source: 'paintings/modern/02-rothko.glsl',
          params: [
            {
              name: 'u_shift',
              label: 'Shift',
              labelZh: '色块偏移',
              min: -0.15,
              max: 0.15,
              step: 0.005,
              default: 0.0,
            },
            {
              name: 'u_breathe_size',
              label: 'Breathe',
              labelZh: '呼吸幅度',
              min: 0,
              max: 0.1,
              step: 0.002,
              default: 0.04,
            },
            {
              name: 'u_mood_color',
              label: 'Mood',
              labelZh: '情绪色调',
              type: 'color',
              defaultColor: [0.7, 0.3, 0.2],
            },
          ],
          presets: [
            {
              name: 'calm',
              nameZh: '宁静',
              values: { u_shift: 0.0, u_breathe_size: 0.02, u_mood_color: [0.3, 0.4, 0.6] },
            },
            {
              name: 'warm',
              nameZh: '温暖',
              values: { u_shift: 0.03, u_breathe_size: 0.05, u_mood_color: [0.7, 0.3, 0.2] },
            },
            {
              name: 'intense',
              nameZh: '强烈',
              values: { u_shift: -0.05, u_breathe_size: 0.08, u_mood_color: [0.9, 0.2, 0.1] },
            },
          ],
          interactive: true,
        },
        {
          id: 'pollock',
          title: 'Drip Painting — Pollock',
          titleZh: '滴画 — 波洛克',
          description: 'Click to splatter new paint; drag to leave drip trails across the canvas.',
          descriptionZh: '点击泼溅新颜料，鼠标拖出流淌轨迹。',
          source: 'paintings/modern/03-pollock.glsl',
          params: [
            {
              name: 'u_density',
              label: 'Density',
              labelZh: '密度',
              min: 0.3,
              max: 2.5,
              step: 0.1,
              default: 1.0,
            },
            {
              name: 'u_speed',
              label: 'Speed',
              labelZh: '演化速度',
              min: 0,
              max: 3,
              step: 0.1,
              default: 1.0,
            },
            {
              name: 'u_splash_color',
              label: 'Splash',
              labelZh: '泼溅色',
              type: 'color',
              defaultColor: [0.9, 0.2, 0.1],
            },
          ],
          presets: [
            {
              name: 'sparse',
              nameZh: '稀疏',
              values: { u_density: 0.5, u_speed: 0.5, u_splash_color: [0.2, 0.5, 0.8] },
            },
            {
              name: 'medium',
              nameZh: '中等',
              values: { u_density: 1.0, u_speed: 1.0, u_splash_color: [0.9, 0.2, 0.1] },
            },
            {
              name: 'dense',
              nameZh: '密集',
              values: { u_density: 2.0, u_speed: 2.0, u_splash_color: [1.0, 0.7, 0.0] },
            },
          ],
          interactive: true,
        },
      ],
    },
    {
      id: 'surrealism',
      title: 'Surrealism',
      titleZh: '超现实主义',
      description: 'Melting clocks and dream-logic distortions.',
      descriptionZh: '融化的时钟与梦的逻辑。',
      demos: [
        {
          id: 'dali-melting',
          title: 'The Persistence of Memory — Dali',
          titleZh: '记忆的永恒 — 达利',
          description: 'Melting clocks droop and distort; mouse proximity accelerates the melt.',
          descriptionZh: '软钟随鼠标融化变形，光标越近融化越快。',
          source: 'paintings/surrealism/01-dali-melting.glsl',
          params: [
            {
              name: 'u_melt_amount',
              label: 'Melt',
              labelZh: '融化程度',
              min: 0,
              max: 1,
              step: 0.02,
              default: 0.5,
            },
            {
              name: 'u_clock_color',
              label: 'Clock',
              labelZh: '钟面色',
              type: 'color',
              defaultColor: [0.9, 0.85, 0.7],
            },
            {
              name: 'u_horizon_color',
              label: 'Horizon',
              labelZh: '地平线色',
              type: 'color',
              defaultColor: [0.55, 0.4, 0.25],
            },
          ],
          presets: [
            {
              name: 'solid',
              nameZh: '坚硬',
              values: {
                u_melt_amount: 0.15,
                u_clock_color: [0.9, 0.85, 0.7],
                u_horizon_color: [0.55, 0.4, 0.25],
              },
            },
            {
              name: 'soften',
              nameZh: '软化',
              values: {
                u_melt_amount: 0.5,
                u_clock_color: [0.85, 0.8, 0.65],
                u_horizon_color: [0.5, 0.35, 0.2],
              },
            },
            {
              name: 'melted',
              nameZh: '融尽',
              values: {
                u_melt_amount: 0.9,
                u_clock_color: [0.7, 0.65, 0.5],
                u_horizon_color: [0.4, 0.3, 0.2],
              },
            },
          ],
          interactive: true,
        },
      ],
    },
    {
      id: 'secession',
      title: 'Vienna Secession',
      titleZh: '维也纳分离派',
      description: 'Gold leaf fragments shimmer and gather around the cursor.',
      descriptionZh: '金箔碎片随鼠标闪烁聚拢。',
      demos: [
        {
          id: 'klimt-kiss',
          title: 'The Kiss — Klimt',
          titleZh: '吻 — 克里姆特',
          description:
            'Golden fragments sparkle and drift toward the mouse; abstract figures in warm embrace.',
          descriptionZh: '金箔碎片闪烁并向光标聚拢，抽象人形在暖色调中相拥。',
          source: 'paintings/secession/01-klimt-kiss.glsl',
          params: [
            {
              name: 'u_sparkle_density',
              label: 'Sparkle',
              labelZh: '闪光密度',
              min: 0.2,
              max: 2,
              step: 0.05,
              default: 1.0,
            },
            {
              name: 'u_gold_hue',
              label: 'Gold',
              labelZh: '金色调',
              min: 0,
              max: 1,
              step: 0.02,
              default: 0.5,
            },
            {
              name: 'u_fragment_size',
              label: 'Fragment',
              labelZh: '碎片大小',
              min: 0.5,
              max: 2,
              step: 0.05,
              default: 1.0,
            },
          ],
          presets: [
            {
              name: 'subtle',
              nameZh: '含蓄',
              values: { u_sparkle_density: 0.5, u_gold_hue: 0.3, u_fragment_size: 0.7 },
            },
            {
              name: 'opulent',
              nameZh: '华丽',
              values: { u_sparkle_density: 1.2, u_gold_hue: 0.5, u_fragment_size: 1.0 },
            },
            {
              name: 'dazzling',
              nameZh: '炫目',
              values: { u_sparkle_density: 1.8, u_gold_hue: 0.7, u_fragment_size: 1.5 },
            },
          ],
          interactive: true,
        },
      ],
    },
  ],
};

registerCategory(paintings);
